sudo: required
services:
  - docker

before_install:
  - docker build -t pheely/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pheely/react-test npm test -- --coverage

after_success:
  # Build containers
  - docker build -t pheely/multi-client ./client
  - docker build -t pheely/multi-nginx ./nginx
  - docker build -t pheely/multi-server ./server
  - docker build -t pheely/multi-worker ./worker

  # Login to docker cli
  # DOCKER_ID and DOCKER_PASSWORD are set in Travis CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  ## Push these images to docker hub
  - docker push pheely/multi-client
  - docker push pheely/multi-nginx
  - docker push pheely/multi-server
  - docker push pheely/multi-worker
  
